// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxazzeswszludevbqqah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4YXp6ZXN3c3psdWRldmJxcWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTE0MDcsImV4cCI6MjA2NjIyNzQwN30.f0nc2Iu6uq7vluWzfM45EsvDC6ffhAidAoIps8W-jcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);